// FanCurva — Badge Definitions
// Auto-generated — do not edit manually

export interface BadgeDefinition {
  badge_id: string
  name: string
  description: string
  badge_type: string
  is_soulbound: boolean
  rarity: number
  primary_color: string
  available_from: string
  available_until: string | null
  max_supply: number | null
  how_to_earn: string
  [key: string]: any
}

export const BADGES: BadgeDefinition[] = [
  {
    "badge_id": "badge_starter",
    "name": "First Step",
    "description": "Awarded for completing your very first quest on FanCurva.",
    "badge_type": "starter",
    "is_soulbound": true,
    "rarity": 1,
    "primary_color": "1D9E75",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Complete your first quest"
  },
  {
    "badge_id": "badge_neutral_fan",
    "name": "Neutral Fan",
    "description": "Your team has been eliminated but your passion remains. Awarded when neutral fan mode activates.",
    "badge_type": "neutral_fan",
    "is_soulbound": true,
    "rarity": 1,
    "primary_color": "888780",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Automatically awarded when your team is eliminated from the tournament"
  },
  {
    "badge_id": "badge_watch_party",
    "name": "Watch Party",
    "description": "Earned for attending or hosting a registered FanCurva watch party.",
    "badge_type": "watch_party",
    "is_soulbound": true,
    "rarity": 1,
    "primary_color": "1D9E75",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Attend or host a registered watch party"
  },
  {
    "badge_id": "badge_watch_party_host",
    "name": "Watch Party Host",
    "description": "Earned for hosting your own FanCurva watch party event.",
    "badge_type": "watch_party",
    "is_soulbound": true,
    "rarity": 1,
    "primary_color": "085041",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Register and host a watch party"
  },
  {
    "badge_id": "badge_trivia_streak_5",
    "name": "Trivia Streak x5",
    "description": "Earned for answering 5 consecutive trivia questions correctly.",
    "badge_type": "trivia_streak",
    "is_soulbound": true,
    "rarity": 1,
    "streak": 5,
    "primary_color": "4A9EFF",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Answer 5 trivia questions correctly in a row"
  },
  {
    "badge_id": "badge_trivia_streak_10",
    "name": "Trivia Streak x10",
    "description": "Earned for answering 10 consecutive trivia questions correctly. A true football scholar.",
    "badge_type": "trivia_streak",
    "is_soulbound": true,
    "rarity": 2,
    "streak": 10,
    "primary_color": "C084FC",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Answer 10 trivia questions correctly in a row"
  },
  {
    "badge_id": "badge_trivia_streak_20",
    "name": "Trivia Streak x20",
    "description": "Answer 20 consecutive trivia questions correctly. Legendary football knowledge.",
    "badge_type": "trivia_streak",
    "is_soulbound": true,
    "rarity": 3,
    "streak": 20,
    "primary_color": "FFD700",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Answer 20 trivia questions correctly in a row"
  },
  {
    "badge_id": "badge_referral_1",
    "name": "Referral — 1 Friend",
    "description": "Earned for successfully referring your first friend to FanCurva.",
    "badge_type": "referral",
    "is_soulbound": true,
    "rarity": 1,
    "referral_count": 1,
    "primary_color": "9FE1CB",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Invite 1 friend who signs up and completes their first quest"
  },
  {
    "badge_id": "badge_referral_5",
    "name": "Referral — 5 Friends",
    "description": "Earned for referring 5 active friends to FanCurva.",
    "badge_type": "referral",
    "is_soulbound": true,
    "rarity": 2,
    "referral_count": 5,
    "primary_color": "1D9E75",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Invite 5 friends who each complete their first quest"
  },
  {
    "badge_id": "badge_referral_10",
    "name": "Referral — 10 Friends",
    "description": "A true FanCurva ambassador. Earned for referring 10 active fans.",
    "badge_type": "referral",
    "is_soulbound": true,
    "rarity": 3,
    "referral_count": 10,
    "primary_color": "085041",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Invite 10 friends who each complete their first quest"
  },
  {
    "badge_id": "badge_legend_tier",
    "name": "Legend",
    "description": "Awarded when you reach the Legend status tier — 3,500+ points. The elite of FanCurva.",
    "badge_type": "legend",
    "is_soulbound": true,
    "rarity": 3,
    "primary_color": "FFD700",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Earn 3,500 or more points during the tournament"
  },
  {
    "badge_id": "badge_finals_week",
    "name": "Finals Week",
    "description": "Earned for active participation during the final week of the World Cup (July 14-19).",
    "badge_type": "finals",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "FFD700",
    "available_from": "2026-07-14T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Complete at least 3 quests during finals week (July 14-19)"
  },
  {
    "badge_id": "badge_early_adopter",
    "name": "Early Adopter",
    "description": "Awarded to fans who joined FanCurva before the tournament began. A mark of being there from the start.",
    "badge_type": "commemorative",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "1D9E75",
    "available_from": "2026-05-01T00:00:00Z",
    "available_until": "2026-06-10T23:59:59Z",
    "max_supply": 10000,
    "how_to_earn": "Sign up and mint your passport before June 11, 2026"
  },
  {
    "badge_id": "badge_perfect_group_stage",
    "name": "Perfect Group Stage",
    "description": "Earned for checking in to every single group stage match — all 72 games.",
    "badge_type": "commemorative",
    "is_soulbound": true,
    "rarity": 3,
    "primary_color": "C084FC",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-06-28T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during all 72 group stage matches"
  },
  {
    "badge_id": "badge_reaction_king",
    "name": "Reaction King",
    "description": "Posted a match reaction after 10 or more matches.",
    "badge_type": "commemorative",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "F97316",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Post a match reaction after 10 or more matches"
  },
  {
    "badge_id": "badge_team_mex",
    "name": "Mexico Team Badge",
    "description": "Official team badge for Mexico fans. Earned when you select Mexico as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "MEX",
    "group": "A",
    "primary_color": "006847",
    "secondary_color": "CE1126",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇲🇽"
  },
  {
    "badge_id": "badge_team_kor",
    "name": "South Korea Team Badge",
    "description": "Official team badge for South Korea fans. Earned when you select South Korea as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "KOR",
    "group": "A",
    "primary_color": "CD2E3A",
    "secondary_color": "003478",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇰🇷"
  },
  {
    "badge_id": "badge_team_rsa",
    "name": "South Africa Team Badge",
    "description": "Official team badge for South Africa fans. Earned when you select South Africa as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "RSA",
    "group": "A",
    "primary_color": "007A4D",
    "secondary_color": "FFB81C",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇿🇦"
  },
  {
    "badge_id": "badge_team_cze",
    "name": "Czechia Team Badge",
    "description": "Official team badge for Czechia fans. Earned when you select Czechia as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "CZE",
    "group": "A",
    "primary_color": "D7141A",
    "secondary_color": "11457E",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇿"
  },
  {
    "badge_id": "badge_team_can",
    "name": "Canada Team Badge",
    "description": "Official team badge for Canada fans. Earned when you select Canada as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "CAN",
    "group": "B",
    "primary_color": "FF0000",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇦"
  },
  {
    "badge_id": "badge_team_sui",
    "name": "Switzerland Team Badge",
    "description": "Official team badge for Switzerland fans. Earned when you select Switzerland as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "SUI",
    "group": "B",
    "primary_color": "D52B1E",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇭"
  },
  {
    "badge_id": "badge_team_qat",
    "name": "Qatar Team Badge",
    "description": "Official team badge for Qatar fans. Earned when you select Qatar as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "QAT",
    "group": "B",
    "primary_color": "8D1B3D",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇶🇦"
  },
  {
    "badge_id": "badge_team_bih",
    "name": "Bosnia and Herzegovina Team Badge",
    "description": "Official team badge for Bosnia and Herzegovina fans. Earned when you select Bosnia and Herzegovina as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "BIH",
    "group": "B",
    "primary_color": "002395",
    "secondary_color": "FFCD00",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇧🇦"
  },
  {
    "badge_id": "badge_team_bra",
    "name": "Brazil Team Badge",
    "description": "Official team badge for Brazil fans. Earned when you select Brazil as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "BRA",
    "group": "C",
    "primary_color": "009C3B",
    "secondary_color": "FFDF00",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇧🇷"
  },
  {
    "badge_id": "badge_team_mar",
    "name": "Morocco Team Badge",
    "description": "Official team badge for Morocco fans. Earned when you select Morocco as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "MAR",
    "group": "C",
    "primary_color": "C1272D",
    "secondary_color": "006233",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇲🇦"
  },
  {
    "badge_id": "badge_team_sco",
    "name": "Scotland Team Badge",
    "description": "Official team badge for Scotland fans. Earned when you select Scotland as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "SCO",
    "group": "C",
    "primary_color": "005EB8",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🏴"
  },
  {
    "badge_id": "badge_team_hai",
    "name": "Haiti Team Badge",
    "description": "Official team badge for Haiti fans. Earned when you select Haiti as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "HAI",
    "group": "C",
    "primary_color": "00209F",
    "secondary_color": "D21034",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇭🇹"
  },
  {
    "badge_id": "badge_team_usa",
    "name": "United States Team Badge",
    "description": "Official team badge for United States fans. Earned when you select United States as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "USA",
    "group": "D",
    "primary_color": "B22234",
    "secondary_color": "3C3B6E",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇺🇸"
  },
  {
    "badge_id": "badge_team_aus",
    "name": "Australia Team Badge",
    "description": "Official team badge for Australia fans. Earned when you select Australia as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "AUS",
    "group": "D",
    "primary_color": "00008B",
    "secondary_color": "FFCD00",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇦🇺"
  },
  {
    "badge_id": "badge_team_par",
    "name": "Paraguay Team Badge",
    "description": "Official team badge for Paraguay fans. Earned when you select Paraguay as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "PAR",
    "group": "D",
    "primary_color": "D52B1E",
    "secondary_color": "002868",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇵🇾"
  },
  {
    "badge_id": "badge_team_tur",
    "name": "Türkiye Team Badge",
    "description": "Official team badge for Türkiye fans. Earned when you select Türkiye as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "TUR",
    "group": "D",
    "primary_color": "E30A17",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇹🇷"
  },
  {
    "badge_id": "badge_team_ger",
    "name": "Germany Team Badge",
    "description": "Official team badge for Germany fans. Earned when you select Germany as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "GER",
    "group": "E",
    "primary_color": "000000",
    "secondary_color": "DD0000",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇩🇪"
  },
  {
    "badge_id": "badge_team_ecu",
    "name": "Ecuador Team Badge",
    "description": "Official team badge for Ecuador fans. Earned when you select Ecuador as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "ECU",
    "group": "E",
    "primary_color": "FFD100",
    "secondary_color": "007934",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇪🇨"
  },
  {
    "badge_id": "badge_team_civ",
    "name": "Ivory Coast Team Badge",
    "description": "Official team badge for Ivory Coast fans. Earned when you select Ivory Coast as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "CIV",
    "group": "E",
    "primary_color": "F77F00",
    "secondary_color": "009A44",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇮"
  },
  {
    "badge_id": "badge_team_cuw",
    "name": "Curaçao Team Badge",
    "description": "Official team badge for Curaçao fans. Earned when you select Curaçao as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "CUW",
    "group": "E",
    "primary_color": "003DA5",
    "secondary_color": "F9E716",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇼"
  },
  {
    "badge_id": "badge_team_ned",
    "name": "Netherlands Team Badge",
    "description": "Official team badge for Netherlands fans. Earned when you select Netherlands as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "NED",
    "group": "F",
    "primary_color": "FF6600",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇳🇱"
  },
  {
    "badge_id": "badge_team_jpn",
    "name": "Japan Team Badge",
    "description": "Official team badge for Japan fans. Earned when you select Japan as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "JPN",
    "group": "F",
    "primary_color": "BC002D",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇯🇵"
  },
  {
    "badge_id": "badge_team_swe",
    "name": "Sweden Team Badge",
    "description": "Official team badge for Sweden fans. Earned when you select Sweden as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "SWE",
    "group": "F",
    "primary_color": "006AA7",
    "secondary_color": "FECC02",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇸🇪"
  },
  {
    "badge_id": "badge_team_tun",
    "name": "Tunisia Team Badge",
    "description": "Official team badge for Tunisia fans. Earned when you select Tunisia as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "TUN",
    "group": "F",
    "primary_color": "E70013",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇹🇳"
  },
  {
    "badge_id": "badge_team_bel",
    "name": "Belgium Team Badge",
    "description": "Official team badge for Belgium fans. Earned when you select Belgium as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "BEL",
    "group": "G",
    "primary_color": "EF3340",
    "secondary_color": "000000",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇧🇪"
  },
  {
    "badge_id": "badge_team_irn",
    "name": "Iran Team Badge",
    "description": "Official team badge for Iran fans. Earned when you select Iran as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "IRN",
    "group": "G",
    "primary_color": "239F40",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇮🇷"
  },
  {
    "badge_id": "badge_team_egy",
    "name": "Egypt Team Badge",
    "description": "Official team badge for Egypt fans. Earned when you select Egypt as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "EGY",
    "group": "G",
    "primary_color": "CE1126",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇪🇬"
  },
  {
    "badge_id": "badge_team_nzl",
    "name": "New Zealand Team Badge",
    "description": "Official team badge for New Zealand fans. Earned when you select New Zealand as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "NZL",
    "group": "G",
    "primary_color": "00247D",
    "secondary_color": "CC142B",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇳🇿"
  },
  {
    "badge_id": "badge_team_esp",
    "name": "Spain Team Badge",
    "description": "Official team badge for Spain fans. Earned when you select Spain as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "ESP",
    "group": "H",
    "primary_color": "AA151B",
    "secondary_color": "F1BF00",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇪🇸"
  },
  {
    "badge_id": "badge_team_uru",
    "name": "Uruguay Team Badge",
    "description": "Official team badge for Uruguay fans. Earned when you select Uruguay as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "URU",
    "group": "H",
    "primary_color": "5EB6E4",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇺🇾"
  },
  {
    "badge_id": "badge_team_ksa",
    "name": "Saudi Arabia Team Badge",
    "description": "Official team badge for Saudi Arabia fans. Earned when you select Saudi Arabia as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "KSA",
    "group": "H",
    "primary_color": "006C35",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇸🇦"
  },
  {
    "badge_id": "badge_team_cpv",
    "name": "Cape Verde Team Badge",
    "description": "Official team badge for Cape Verde fans. Earned when you select Cape Verde as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "CPV",
    "group": "H",
    "primary_color": "003893",
    "secondary_color": "CF2027",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇻"
  },
  {
    "badge_id": "badge_team_fra",
    "name": "France Team Badge",
    "description": "Official team badge for France fans. Earned when you select France as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "FRA",
    "group": "I",
    "primary_color": "002395",
    "secondary_color": "ED2939",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇫🇷"
  },
  {
    "badge_id": "badge_team_sen",
    "name": "Senegal Team Badge",
    "description": "Official team badge for Senegal fans. Earned when you select Senegal as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "SEN",
    "group": "I",
    "primary_color": "00853F",
    "secondary_color": "FDEF42",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇸🇳"
  },
  {
    "badge_id": "badge_team_nor",
    "name": "Norway Team Badge",
    "description": "Official team badge for Norway fans. Earned when you select Norway as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "NOR",
    "group": "I",
    "primary_color": "EF2B2D",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇳🇴"
  },
  {
    "badge_id": "badge_team_irq",
    "name": "Iraq Team Badge",
    "description": "Official team badge for Iraq fans. Earned when you select Iraq as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "IRQ",
    "group": "I",
    "primary_color": "CE1126",
    "secondary_color": "007A3D",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇮🇶"
  },
  {
    "badge_id": "badge_team_arg",
    "name": "Argentina Team Badge",
    "description": "Official team badge for Argentina fans. Earned when you select Argentina as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "ARG",
    "group": "J",
    "primary_color": "74ACDF",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇦🇷"
  },
  {
    "badge_id": "badge_team_aut",
    "name": "Austria Team Badge",
    "description": "Official team badge for Austria fans. Earned when you select Austria as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "AUT",
    "group": "J",
    "primary_color": "ED2939",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇦🇹"
  },
  {
    "badge_id": "badge_team_alg",
    "name": "Algeria Team Badge",
    "description": "Official team badge for Algeria fans. Earned when you select Algeria as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "ALG",
    "group": "J",
    "primary_color": "006233",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇩🇿"
  },
  {
    "badge_id": "badge_team_jor",
    "name": "Jordan Team Badge",
    "description": "Official team badge for Jordan fans. Earned when you select Jordan as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "JOR",
    "group": "J",
    "primary_color": "007A3D",
    "secondary_color": "CE1126",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇯🇴"
  },
  {
    "badge_id": "badge_team_por",
    "name": "Portugal Team Badge",
    "description": "Official team badge for Portugal fans. Earned when you select Portugal as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "POR",
    "group": "K",
    "primary_color": "006600",
    "secondary_color": "FF0000",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇵🇹"
  },
  {
    "badge_id": "badge_team_col",
    "name": "Colombia Team Badge",
    "description": "Official team badge for Colombia fans. Earned when you select Colombia as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "COL",
    "group": "K",
    "primary_color": "FCD116",
    "secondary_color": "003087",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇴"
  },
  {
    "badge_id": "badge_team_uzb",
    "name": "Uzbekistan Team Badge",
    "description": "Official team badge for Uzbekistan fans. Earned when you select Uzbekistan as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "UZB",
    "group": "K",
    "primary_color": "1EB53A",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇺🇿"
  },
  {
    "badge_id": "badge_team_cod",
    "name": "DR Congo Team Badge",
    "description": "Official team badge for DR Congo fans. Earned when you select DR Congo as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "COD",
    "group": "K",
    "primary_color": "007FFF",
    "secondary_color": "F7D618",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇨🇩"
  },
  {
    "badge_id": "badge_team_eng",
    "name": "England Team Badge",
    "description": "Official team badge for England fans. Earned when you select England as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "ENG",
    "group": "L",
    "primary_color": "CF081F",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🏴"
  },
  {
    "badge_id": "badge_team_cro",
    "name": "Croatia Team Badge",
    "description": "Official team badge for Croatia fans. Earned when you select Croatia as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "CRO",
    "group": "L",
    "primary_color": "FF0000",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇭🇷"
  },
  {
    "badge_id": "badge_team_gha",
    "name": "Ghana Team Badge",
    "description": "Official team badge for Ghana fans. Earned when you select Ghana as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "GHA",
    "group": "L",
    "primary_color": "006B3F",
    "secondary_color": "FCD116",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇬🇭"
  },
  {
    "badge_id": "badge_team_pan",
    "name": "Panama Team Badge",
    "description": "Official team badge for Panama fans. Earned when you select Panama as your team and mint your passport.",
    "badge_type": "team",
    "is_soulbound": true,
    "rarity": 1,
    "team_code": "PAN",
    "group": "L",
    "primary_color": "DA121A",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-01T00:00:00Z",
    "available_until": null,
    "max_supply": null,
    "how_to_earn": "Select this team during passport creation",
    "icon": "🇵🇦"
  },
  {
    "badge_id": "badge_match_m001",
    "name": "MEX vs KOR — Match Day",
    "description": "Earned for checking in during the MEX vs KOR Group A match on 2026-06-11.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m001",
    "match_date": "2026-06-11",
    "venue": "SoFi Stadium, Los Angeles",
    "home_team": "MEX",
    "away_team": "KOR",
    "group": "A",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-06-11T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-11"
  },
  {
    "badge_id": "badge_match_m002",
    "name": "BRA vs MAR — Match Day",
    "description": "Earned for checking in during the BRA vs MAR Group C match on 2026-06-12.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m002",
    "match_date": "2026-06-12",
    "venue": "AT&T Stadium, Dallas",
    "home_team": "BRA",
    "away_team": "MAR",
    "group": "C",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-12T00:00:00Z",
    "available_until": "2026-06-12T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-12"
  },
  {
    "badge_id": "badge_match_m003",
    "name": "USA vs PAR — Match Day",
    "description": "Earned for checking in during the USA vs PAR Group D match on 2026-06-12.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m003",
    "match_date": "2026-06-12",
    "venue": "MetLife Stadium, New York",
    "home_team": "USA",
    "away_team": "PAR",
    "group": "D",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-12T00:00:00Z",
    "available_until": "2026-06-12T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-12"
  },
  {
    "badge_id": "badge_match_m004",
    "name": "ARG vs ALG — Match Day",
    "description": "Earned for checking in during the ARG vs ALG Group J match on 2026-06-13.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m004",
    "match_date": "2026-06-13",
    "venue": "Hard Rock Stadium, Miami",
    "home_team": "ARG",
    "away_team": "ALG",
    "group": "J",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-13T00:00:00Z",
    "available_until": "2026-06-13T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-13"
  },
  {
    "badge_id": "badge_match_m005",
    "name": "ENG vs CRO — Match Day",
    "description": "Earned for checking in during the ENG vs CRO Group L match on 2026-06-13.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m005",
    "match_date": "2026-06-13",
    "venue": "Empower Field, Denver",
    "home_team": "ENG",
    "away_team": "CRO",
    "group": "L",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-13T00:00:00Z",
    "available_until": "2026-06-13T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-13"
  },
  {
    "badge_id": "badge_match_m006",
    "name": "FRA vs SEN — Match Day",
    "description": "Earned for checking in during the FRA vs SEN Group I match on 2026-06-14.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m006",
    "match_date": "2026-06-14",
    "venue": "Gillette Stadium, Boston",
    "home_team": "FRA",
    "away_team": "SEN",
    "group": "I",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-14T00:00:00Z",
    "available_until": "2026-06-14T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-14"
  },
  {
    "badge_id": "badge_match_m007",
    "name": "GER vs ECU — Match Day",
    "description": "Earned for checking in during the GER vs ECU Group E match on 2026-06-14.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m007",
    "match_date": "2026-06-14",
    "venue": "Lumen Field, Seattle",
    "home_team": "GER",
    "away_team": "ECU",
    "group": "E",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-14T00:00:00Z",
    "available_until": "2026-06-14T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-14"
  },
  {
    "badge_id": "badge_match_m008",
    "name": "ESP vs URU — Match Day",
    "description": "Earned for checking in during the ESP vs URU Group H match on 2026-06-15.",
    "badge_type": "match_day",
    "is_soulbound": true,
    "rarity": 1,
    "match_id": "m008",
    "match_date": "2026-06-15",
    "venue": "Arrowhead Stadium, Kansas City",
    "home_team": "ESP",
    "away_team": "URU",
    "group": "H",
    "primary_color": "4A9EFF",
    "available_from": "2026-06-15T00:00:00Z",
    "available_until": "2026-06-15T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the live match on 2026-06-15"
  },
  {
    "badge_id": "badge_city_usa",
    "name": "USA Host City Badge",
    "description": "Earned for engaging with US host city content and campaigns during the 2026 World Cup.",
    "badge_type": "city",
    "is_soulbound": true,
    "rarity": 1,
    "country": "USA",
    "primary_color": "B22234",
    "secondary_color": "3C3B6E",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Complete 3 USA host city quests",
    "venues": [
      "MetLife Stadium NY",
      "SoFi Stadium LA",
      "AT&T Stadium Dallas",
      "Lumen Field Seattle",
      "Empower Field Denver",
      "Gillette Stadium Boston",
      "Arrowhead Stadium Kansas City",
      "Allegiant Stadium Las Vegas",
      "Lincoln Financial Field Philadelphia",
      "NRG Stadium Houston"
    ]
  },
  {
    "badge_id": "badge_city_canada",
    "name": "Canada Host City Badge",
    "description": "Earned for engaging with Canadian host city content and campaigns during the 2026 World Cup.",
    "badge_type": "city",
    "is_soulbound": true,
    "rarity": 1,
    "country": "Canada",
    "primary_color": "FF0000",
    "secondary_color": "FFFFFF",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Complete 3 Canada host city quests",
    "venues": [
      "BC Place, Vancouver",
      "BMO Field, Toronto"
    ]
  },
  {
    "badge_id": "badge_city_mexico",
    "name": "Mexico Host City Badge",
    "description": "Earned for engaging with Mexican host city content and campaigns during the 2026 World Cup.",
    "badge_type": "city",
    "is_soulbound": true,
    "rarity": 1,
    "country": "Mexico",
    "primary_color": "006847",
    "secondary_color": "CE1126",
    "available_from": "2026-06-11T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Complete 3 Mexico host city quests",
    "venues": [
      "Estadio Azteca, Mexico City",
      "Estadio BBVA, Monterrey",
      "Estadio Akron, Guadalajara"
    ]
  },
  {
    "badge_id": "badge_round_of_32",
    "name": "Round of 32",
    "description": "Earned for checking in during a Round of 32 knockout match.",
    "badge_type": "knockout",
    "stage": "Round of 32",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "4A9EFF",
    "available_from": "2026-06-28T00:00:00Z",
    "available_until": "2026-07-01T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during any Round of 32 match"
  },
  {
    "badge_id": "badge_round_of_16",
    "name": "Round of 16",
    "description": "Earned for checking in during a Round of 16 knockout match.",
    "badge_type": "knockout",
    "stage": "Round of 16",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "4A9EFF",
    "available_from": "2026-07-02T00:00:00Z",
    "available_until": "2026-07-05T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during any Round of 16 match"
  },
  {
    "badge_id": "badge_quarter_final",
    "name": "Quarter Final",
    "description": "Earned for checking in during a Quarter Final match.",
    "badge_type": "knockout",
    "stage": "Quarter Final",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "C084FC",
    "available_from": "2026-07-08T00:00:00Z",
    "available_until": "2026-07-09T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during any Quarter Final match"
  },
  {
    "badge_id": "badge_semi_final",
    "name": "Semi Final",
    "description": "Earned for checking in during a Semi Final match.",
    "badge_type": "knockout",
    "stage": "Semi Final",
    "is_soulbound": true,
    "rarity": 3,
    "primary_color": "C084FC",
    "available_from": "2026-07-14T00:00:00Z",
    "available_until": "2026-07-15T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during either Semi Final match"
  },
  {
    "badge_id": "badge_third_place",
    "name": "Third Place Match",
    "description": "Earned for checking in during the Third Place match.",
    "badge_type": "knockout",
    "stage": "Third Place",
    "is_soulbound": true,
    "rarity": 2,
    "primary_color": "CD7F32",
    "available_from": "2026-07-18T00:00:00Z",
    "available_until": "2026-07-18T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the Third Place match on July 18"
  },
  {
    "badge_id": "badge_finals",
    "name": "Finals Badge",
    "description": "Earned for checking in during the World Cup Final. One of the rarest badges of the tournament.",
    "badge_type": "knockout",
    "stage": "Final",
    "is_soulbound": true,
    "rarity": 3,
    "primary_color": "FFD700",
    "available_from": "2026-07-19T00:00:00Z",
    "available_until": "2026-07-19T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Check in during the World Cup Final on July 19"
  },
  {
    "badge_id": "badge_champion",
    "name": "Champion",
    "description": "The rarest badge of the 2026 World Cup. Awarded exclusively to fans whose team wins the tournament.",
    "badge_type": "champion",
    "stage": "Champion",
    "is_soulbound": true,
    "rarity": 4,
    "primary_color": "FFD700",
    "available_from": "2026-07-19T00:00:00Z",
    "available_until": "2026-07-20T23:59:59Z",
    "max_supply": null,
    "how_to_earn": "Support the winning team throughout the tournament"
  }
]

export const BADGES_BY_ID: Record<string, BadgeDefinition> = Object.fromEntries(
  BADGES.map(b => [b.badge_id, b])
)

export const BADGES_BY_TYPE: Record<string, BadgeDefinition[]> = BADGES.reduce((acc, b) => {
  if (!acc[b.badge_type]) acc[b.badge_type] = []
  acc[b.badge_type].push(b)
  return acc
}, {} as Record<string, BadgeDefinition[]>)

export const RARITY_LABELS: Record<number, string> = {
  1: 'Common',
  2: 'Uncommon',
  3: 'Rare',
  4: 'Legendary',
}
